#version: "3"

services:

  # ------------------------------------------------------
  # medienhaus-spaces
  # ------------------------------------------------------

  configure-medienhaus-spaces:
    image: busybox:latest
    container_name: configure-medienhaus-spaces
    env_file:
      - .env
    command: >
      sed -i
          -e "s/\$${MATRIX_CONTEXT_ROOT}/${MATRIX_CONTEXT_ROOT}/g"
          /tmp/medienhaus-spaces.config.js
    volumes:
      #- ./config/medienhaus-spaces.config.js:/tmp/medienhaus-spaces.config.js:rw
      - ./config:/tmp:rw

# ------------------------------------------------------
# networks (example)
# ------------------------------------------------------

#networks:
#  default:
#    driver: bridge

# ------------------------------------------------------
# volumes (example)
# ------------------------------------------------------

#volumes:
#  medienhaus_data:
#    driver: local
