services:

  # ------------------------------------------------------
  # medienhaus-spaces
  # ------------------------------------------------------

  medienhaus-spaces:
    build:
      context: ./medienhaus-spaces
      target: "development-runner"
    container_name: medienhaus-spaces
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      NODE_ENV: "development"
      # NOTE: enable detecting `next.config.js` file changes in running container
      # via: https://github.com/vercel/next.js/issues/36774#issuecomment-1438324196
      WATCHPACK_POLLING: "true"
    labels:
      traefik.enable: "true"
      #traefik.http.routers.medienhaus-spaces.entrypoints: "web"
      traefik.http.routers.medienhaus-spaces.entrypoints: "websecure"
      traefik.http.routers.medienhaus-spaces.tls.certresolver: "myresolver"
      traefik.http.routers.medienhaus-spaces.rule: "Host(`${SPACES_HOSTNAME}`)"
    #ports:
    #  - "3000:3000"
    volumes:
      - ./config/medienhaus-spaces.config.js:/app/config.js:ro
      - ./medienhaus-spaces:/app:rw
      - medienhaus-spaces--node_modules:/app/node_modules:rw
      - medienhaus-spaces--.next:/app/.next:rw

  element-medienhaus-spaces:
    image: vectorim/element-web:latest
    container_name: element-medienhaus-spaces
    restart: unless-stopped
    depends_on:
      - traefik
      - medienhaus-spaces
    labels:
      traefik.enable: "true"
      #traefik.http.routers.element-medienhaus-spaces.entrypoints: "web"
      traefik.http.routers.element-medienhaus-spaces.entrypoints: "websecure"
      traefik.http.routers.element-medienhaus-spaces.tls.certresolver: "myresolver"
      traefik.http.routers.element-medienhaus-spaces.rule: "Host(`${SPACES_HOSTNAME}`) && PathPrefix(`/element/`)"
      traefik.http.routers.element-medienhaus-spaces.middlewares: "element-medienhaus-spaces@docker"
      traefik.http.middlewares.element-medienhaus-spaces.stripprefix.prefixes: "/element"
    volumes:
      - ./config/element-medienhaus-spaces.json:/app/config.json:ro

# ------------------------------------------------------
# networks (example)
# ------------------------------------------------------

#networks:
#  default:
#    name: medienhaus-spaces
#    driver: bridge
#    external: true

# ------------------------------------------------------
# volumes
# ------------------------------------------------------

volumes:
  medienhaus-spaces--node_modules:
    driver: local
  medienhaus-spaces--.next:
    driver: local
