services:

  # ------------------------------------------------------
  # medienhaus-api
  # ------------------------------------------------------

  medienhaus-api:
    build: ./medienhaus-api
    container_name: medienhaus-api
    restart: unless-stopped
    depends_on:
      - traefik
      - matrix-synapse
    environment:
      API_PORT: "3000"
      NODE_ENV: "development"
    labels:
      traefik.enable: "true"
      #traefik.http.routers.medienhaus-api.entrypoints: "web"
      traefik.http.routers.medienhaus-api.entrypoints: "websecure"
      traefik.http.routers.medienhaus-api.tls.certresolver: "myresolver"
      traefik.http.routers.medienhaus-api.rule: "Host(`api.${SPACES_HOSTNAME}`)"
    #ports:
    #  - "3000:3000"
    volumes:
      - ./config/medienhaus-api.config.js:/usr/src/app/config.js:ro
      - ./medienhaus-api:/usr/src/app:rw
      - medienhaus-api--node_modules:/usr/src/app/node_modules:rw

# ------------------------------------------------------
# networks (example)
# ------------------------------------------------------

#networks:
#  default:
#    name: medienhaus-spaces
#    driver: bridge
#    external: true

# ------------------------------------------------------
# volumes
# ------------------------------------------------------

volumes:
  medienhaus-api--node_modules:
    driver: local
