#version: "3"

services:

  # ------------------------------------------------------
  # etherpad
  # ------------------------------------------------------

  configure-nginx-etherpad:
    image: busybox:latest
    container_name: configure-nginx-etherpad
    env_file:
      - .env
    command: >
      sed -i
          -e "s/\$${HTTP_SCHEMA}/${HTTP_SCHEMA}/g"
          -e "s/\$${SPACES_HOSTNAME}/${SPACES_HOSTNAME}/g"
          /tmp/nginx-etherpad.conf
    volumes:
      #- ./config/nginx-etherpad.conf:/tmp/nginx-etherpad.conf:rw
      - ./config:/tmp:rw

  configure-etherpad:
    image: busybox:latest
    container_name: configure-etherpad
    env_file:
      - .env
    command: >
      sed -i
          -e "s/\$${ETHERPAD_POSTGRES_PASSWORD}/${ETHERPAD_POSTGRES_PASSWORD}/g"
          -e "s/\$${ETHERPAD_ADMIN_PASSWORD}/${ETHERPAD_ADMIN_PASSWORD}/g"
          /tmp/etherpad.json
    volumes:
      #- ./config/etherpad.json:/tmp/etherpad.json:rw
      - ./config:/tmp:rw

  configure-etherpad-mypads-extra-html-javascript:
    image: busybox:latest
    container_name: configure-etherpad-mypads-extra-html-javascript
    env_file:
      - .env
    command: >
      sed -i
          -e "s/\$${HTTP_SCHEMA}/${HTTP_SCHEMA}/g"
          -e "s/\$${SPACES_HOSTNAME}/${SPACES_HOSTNAME}/g"
          /tmp/etherpad-mypads-extra-html-javascript.html
    volumes:
      #- ./config/etherpad-mypads-extra-html-javascript.html:/tmp/etherpad-mypads-extra-html-javascript.html:rw
      - ./config:/tmp:rw

  configure-etherpad-mypads-ldap-configuration:
    image: busybox:latest
    container_name: configure-etherpad-mypads-ldap-configuration
    env_file:
      - .env
    command: >
      sed -i
          -e "s/\$${LDAP_SCHEMA}/${LDAP_SCHEMA}/g"
          -e "s/\$${LDAP_HOST}/${LDAP_HOST}/g"
          -e "s/\$${LDAP_PORT}/${LDAP_PORT}/g"
          -e "s/\$${LDAP_SEARCH_BASE}/${LDAP_SEARCH_BASE}/g"
          -e "s/\$${LDAP_ATTRIBUTE_UID}/${LDAP_ATTRIBUTE_UID}/g"
          -e "s/\$${LDAP_ATTRIBUTE_MAIL}/${LDAP_ATTRIBUTE_MAIL}/g"
          -e "s/\$${LDAP_ATTRIBUTE_NAME}/${LDAP_ATTRIBUTE_NAME}/g"
          -e "s/\$${LDAP_ATTRIBUTE_FIRSTNAME}/${LDAP_ATTRIBUTE_FIRSTNAME}/g"
          -e "s/\$${LDAP_ATTRIBUTE_LASTNAME}/${LDAP_ATTRIBUTE_LASTNAME}/g"
          -e "s/\$${LDAP_BIND_DN}/${LDAP_BIND_DN}/g"
          -e "s/\$${LDAP_BIND_PASSWORD}/${LDAP_BIND_PASSWORD}/g"
          /tmp/etherpad-mypads-ldap-configuration.json
    volumes:
      #- ./config/etherpad-mypads-ldap-configuration.json:/tmp/etherpad-mypads-ldap-configuration.json:rw
      - ./config:/tmp:rw

  # ------------------------------------------------------
  # spacedeck
  # ------------------------------------------------------

  configure-nginx-spacedeck:
    image: busybox:latest
    container_name: configure-nginx-spacedeck
    env_file:
      - .env
    command: >
      sed -i
          -e "s/\$${HTTP_SCHEMA}/${HTTP_SCHEMA}/g"
          -e "s/\$${SPACES_HOSTNAME}/${SPACES_HOSTNAME}/g"
          /tmp/nginx-spacedeck.conf
    volumes:
      #- ./config/nginx-spacedeck.conf:/tmp/spacedeck-etherpad.conf:rw
      - ./config:/tmp:rw

  configure-spacedeck:
    image: busybox:latest
    container_name: configure-spacedeck
    env_file:
      - .env
    command: >
      sed -i
          -e "s/\$${SPACEDECK_INVITE_CODE}/${SPACEDECK_INVITE_CODE}/g"
          -e "s/\$${SPACEDECK_SESSION_KEY}/${SPACEDECK_SESSION_KEY}/g"
          -e "s/\$${SPACEDECK_EXPORT_API_SECRET}/${SPACEDECK_EXPORT_API_SECRET}/g"
          -e "s/\$${SPACEDECK_POSTGRES_PASSWORD}/${SPACEDECK_POSTGRES_PASSWORD}/g"
          -e "s/\$${LDAP_SCHEMA}/${LDAP_SCHEMA}/g"
          -e "s/\$${LDAP_HOST}/${LDAP_HOST}/g"
          -e "s/\$${LDAP_PORT}/${LDAP_PORT}/g"
          -e "s/\$${LDAP_SEARCH_BASE}/${LDAP_SEARCH_BASE}/g"
          -e "s/\$${LDAP_ATTRIBUTE_UID}/${LDAP_ATTRIBUTE_UID}/g"
          -e "s/\$${LDAP_ATTRIBUTE_MAIL}/${LDAP_ATTRIBUTE_MAIL}/g"
          -e "s/\$${LDAP_ATTRIBUTE_NAME}/${LDAP_ATTRIBUTE_NAME}/g"
          -e "s/\$${LDAP_BIND_DN}/${LDAP_BIND_DN}/g"
          -e "s/\$${LDAP_BIND_PASSWORD}/${LDAP_BIND_PASSWORD}/g"
          /tmp/spacedeck.json
    volumes:
      #- ./config/spacedeck.json:/tmp/spacedeck.json:rw
      - ./config:/tmp:rw

  # ------------------------------------------------------
  # matrix-synapse
  # ------------------------------------------------------

  configure-nginx-matrix-synapse:
    image: busybox:latest
    container_name: configure-nginx-matrix-synapse
    env_file:
      - .env
    command: >
      sed -i
          -e "s/\$${HTTP_SCHEMA}/${HTTP_SCHEMA}/g"
          -e "s/\$${MATRIX_BASEURL}/${MATRIX_BASEURL}/g"
          /tmp/nginx-matrix-synapse.conf
    volumes:
      #- ./config/nginx-matrix-synapse.conf:/tmp/nginx-matrix-synapse.conf:rw
      - ./config:/tmp:rw

  configure-matrix-synapse:
    image: busybox:latest
    container_name: configure-matrix-synapse
    env_file:
      - .env
    command: >
      sed -i
          -e "s/\$${HTTP_SCHEMA}/${HTTP_SCHEMA}/g"
          -e "s/\$${MATRIX_SERVERNAME}/${MATRIX_SERVERNAME}/g"
          -e "s/\$${MATRIX_BASEURL}/${MATRIX_BASEURL}/g"
          -e "s/\$${MATRIX_POSTGRES_PASSWORD}/${MATRIX_POSTGRES_PASSWORD}/g"
          -e "s/\$${LDAP_SCHEMA}/${LDAP_SCHEMA}/g"
          -e "s/\$${LDAP_HOST}/${LDAP_HOST}/g"
          -e "s/\$${LDAP_PORT}/${LDAP_PORT}/g"
          -e "s/\$${LDAP_STARTTLS}/${LDAP_STARTTLS}/g"
          -e "s/\$${LDAP_SEARCH_BASE}/${LDAP_SEARCH_BASE}/g"
          -e "s/\$${LDAP_ATTRIBUTE_UID}/${LDAP_ATTRIBUTE_UID}/g"
          -e "s/\$${LDAP_ATTRIBUTE_MAIL}/${LDAP_ATTRIBUTE_MAIL}/g"
          -e "s/\$${LDAP_ATTRIBUTE_NAME}/${LDAP_ATTRIBUTE_NAME}/g"
          -e "s/\$${LDAP_BIND_DN}/${LDAP_BIND_DN}/g"
          -e "s/\$${LDAP_BIND_PASSWORD}/${LDAP_BIND_PASSWORD}/g"
          -e "s/\$${MATRIX_REGISTRATION_SECRET}/${MATRIX_REGISTRATION_SECRET}/g"
          -e "s/\$${MATRIX_MACAROON_SECRET_KEY}/${MATRIX_MACAROON_SECRET_KEY}/g"
          -e "s/\$${MATRIX_FORM_SECRET}/${MATRIX_FORM_SECRET}/g"
          /tmp/matrix-synapse.yaml
    volumes:
      #- ./config/matrix-synapse.yaml:/tmp/matrix-synapse.yaml:rw
      - ./config:/tmp:rw

  # ------------------------------------------------------
  # element
  # ------------------------------------------------------

  configure-element:
    image: busybox:latest
    container_name: configure-element
    env_file:
      - .env
    command: >
      sed -i
          -e "s/\$${HTTP_SCHEMA}/${HTTP_SCHEMA}/g"
          -e "s/\$${MATRIX_BASEURL}/${MATRIX_BASEURL}/g"
          -e "s/\$${MATRIX_SERVERNAME}/${MATRIX_SERVERNAME}/g"
          /tmp/element.json
    volumes:
      #- ./config/element.json:/tmp/element.json:rw
      - ./config:/tmp:rw

  # ------------------------------------------------------
  # medienhaus-spaces
  # ------------------------------------------------------

  configure-medienhaus-spaces:
    image: busybox:latest
    container_name: configure-medienhaus-spaces
    env_file:
      - .env
    command: >
      sed -i
          -e "s/\$${SPACES_APP_PREFIX}/${SPACES_APP_PREFIX}/g"
          -e "s/\$${HTTP_SCHEMA}/${HTTP_SCHEMA}/g"
          -e "s/\$${MATRIX_BASEURL}/${MATRIX_BASEURL}/g"
          -e "s/\$${SPACES_HOSTNAME}/${SPACES_HOSTNAME}/g"
          /tmp/medienhaus-spaces.config.js
    volumes:
      #- ./config/medienhaus-spaces.config.js:/tmp/medienhaus-spaces.config.js:rw
      - ./config:/tmp:rw

  #configure-element-medienhaus-spaces:
  #  image: busybox:latest
  #  container_name: configure-element-medienhaus-spaces
  #  env_file:
  #    - .env
  #  command: >
  #    sed -i
  #        -e "s/\$${}/${}/g"
  #        /tmp/element-medienhaus-spaces.json
  #  volumes:
  #    #- ./config/element-medienhaus-spaces.json:/tmp/element-medienhaus-spaces.json:rw
  #    - ./config:/tmp:rw

  # ------------------------------------------------------
  # medienhaus-api
  # ------------------------------------------------------

  configure-medienhaus-api:
    image: busybox:latest
    container_name: configure-medienhaus-api
    env_file:
      - .env
    command: >
      sed -i
          -e "s/\$${HTTP_SCHEMA}/${HTTP_SCHEMA}/g"
          -e "s/\$${MATRIX_BASEURL}/${MATRIX_BASEURL}/g"
          /tmp/medienhaus-api.config.js
    volumes:
      #- ./config/medienhaus-api.config.js:/tmp/medienhaus-api.config.js:rw
      - ./config:/tmp:rw

  # ------------------------------------------------------
  # medienhaus-cms
  # ------------------------------------------------------

  #configure-nginx-medienhaus-cms:
  #  image: busybox:latest
  #  container_name: configure-nginx-medienhaus-cms
  #  env_file:
  #    - .env
  #  command: >
  #    sed -i
  #        -e "s/\$${SPACES_HOSTNAME}/${SPACES_HOSTNAME}/g"
  #        /tmp/nginx-matrix-synapse.conf
  #  volumes:
  #    #- ./config/nginx-medienhaus-cms:/tmp/nginx-medienhaus-cms:rw
  #    - ./config:/tmp:rw

  configure-medienhaus-cms:
  #configure-medienhaus-cms-env:
    image: busybox:latest
    container_name: configure-medienhaus-cms
    #container_name: configure-medienhaus-cms-env
    env_file:
      - .env
    command: >
      sed -i
          -e "s/\$${SPACES_APP_PREFIX}/${SPACES_APP_PREFIX}/g"
          -e "s/\$${HTTP_SCHEMA}/${HTTP_SCHEMA}/g"
          -e "s/\$${MATRIX_BASEURL}/${MATRIX_BASEURL}/g"
          -e "s/\$${SPACES_HOSTNAME}/${SPACES_HOSTNAME}/g"
          /tmp/medienhaus-cms.env
    volumes:
      #- ./config/medienhaus-cms.env:/tmp/medienhaus-cms.env:rw
      - ./config:/tmp:rw

  #configure-medienhaus-cms-config:
  #  image: busybox:latest
  #  container_name: configure-medienhaus-cms-config
  #  env_file:
  #    - .env
  #  command: >
  #    sed -i
  #        -e "s/\$${}/${}/g"
  #        /tmp/medienhaus-cms.config.json
  #  volumes:
  #    #- ./config/medienhaus-cms.config.json:/tmp/medienhaus-cms.config.json:rw
  #    - ./config:/tmp:rw

# ------------------------------------------------------
# networks (example)
# ------------------------------------------------------

#networks:
#  default:
#    driver: bridge

# ------------------------------------------------------
# volumes (example)
# ------------------------------------------------------

#volumes:
#  medienhaus_data:
#    driver: local
