# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html

server_name: "matrix.localhost"

pid_file: "/data/homeserver.pid"

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      #- names: [client, federation]
      - names: [client]
        compress: false

database:
  #name: sqlite3
  #args:
  #  database: "/data/homeserver.db"
  name: psycopg2
  args:
    host: postgres-matrix-synapse
    database: synapse
    user: synapse
    password: super_sudo
    cp_min: 5
    cp_max: 10

#log_config: "/data/matrix.localhost.log.config"

media_store_path: "/data/media_store"

enable_registration: true

enable_registration_without_verification: true

registration_shared_secret: "AU5l67odPUe52aazjcQ^7ilL#bKiV.A_DKAEn*fe:d^I#WBKrt"

report_stats: false

macaroon_secret_key: "kItU1V5td-AkFdPRK24x=DIEPWZBeHUkWF.O7STHZkao**S4E*"

form_secret: "H0:-S,s5*@~-Mje5FUicaVcQhzdN0sIhR3i&Y7aRhhjB7,4Q;n"

signing_key_path: "/data/matrix.localhost.signing.key"

trusted_key_servers:
  - server_name: "matrix.org"
